apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aboutphilippe/argo-example.git
    targetRevision: HEAD
    path: apps/guestbook/source/helm-guestbook
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: 'ingress.hosts[0]'
          value: guestbook2.argocd-philippe.restack.sh
        - name: "ingress.annotations.kubernetes\\.io/ingress\\.class"
          value: "nginx"
        - name: service.type
          value: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: default